
#' Generate URL for Survivor Grid Pick Distributions by Year
#'
#' @param season integer, year for pulling game history
#'
#' @return character, url for PFR game result webpage for selected season
#' @export
#'
generate_url_survgrid <- function(season, week) {
  paste0("https://www.survivorgrid.com/", season, "/", week)
}


url <- generate_url_survgrid(2017, 5)


#' Scape game results from survivor grid
#'
#' @param url character, url generated by generate_url_survgrid
#' @param delay integer, seconds delay after requesting page
#'
#' @return dataframe, containing pick distribution data for selected season
#' @export
#'
scrape_survgrid <- function(url, delay = 0) {
  
  # Load raw results
  response <-
    url %>%
    xml2::read_html() %>%
    rvest::html_node("#grid") %>%
    rvest::html_table() %>%
    select(
      team = Team,
      pick_pct = `P%`,
      win_prob = `W%`,
      expected_value = EV
    )
  
  # Delay (optional)
  Sys.sleep(delay)
  
  return(response)
}




