
#' Generate URL for Pro-Football-Reference Game History by Year
#'
#' @param year integer, year for pulling game history
#'
#' @return character, url for PFR game result webpage for selected year
#' @export
#'
generate_url_pfr <- function(year) {
  paste0("https://www.pro-football-reference.com/years/", year, "/games.htm")
}




#' Scape game results from pro-football-reference
#'
#' @param url character, url generated by generate_url_pfr
#' @param delay integer, seconds delay after requesting page
#'
#' @return dataframe, containing game results for selected year
#' @export
#'
scrape_pfr <- function(url, delay = 0) {
  
  # Load raw results
  results <-
    url %>%
    xml2::read_html() %>%
    rvest::html_node("#games") %>%
    rvest::html_table()
  
  # Fix column names
  names(results) <- c(
    "week", 
    "day", 
    "date", 
    "time", 
    "winner",
    "at_indicator", 
    "loser",
    "link_boxscore",
    "points_winner", 
    "points_loser", 
    "yards_winner", 
    "turnovers_winner", 
    "yards_loser", 
    "turnovers_loser"
  )
  
  # Delay (optional)
  Sys.sleep(delay)
  
  return(results)
}




